spring:
  kafka:
    topic:
      group-id: math-question
      topic-name:
        - math-question-generate
    bootstrap-servers: 127.0.0.1:9092,127.0.0.2:9092,127.0.0.3:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1
    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
#  security:
#    user:
#      name: zhangjunyang
#      password: 666666
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: zhangqi1112
    url: jdbc:mysql://localhost:3306/mathforhim1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
#    username: happy1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle:10
      maximum-pool-size:20
      idle-timeout:500000
      max-lifetime:540000
      connection-timeout:60000
      connection-test-query:SELECT 1




server:
  port: 80

aliyun:
  facerec:
    regionId: cn-shanghai
    accessKeyId: LTAI5tLtZSiXoBHpg1osBEX6
    accessKeySecret: JPOaJJypeV2k3yYTSMJdqCw9ME4bu1

math:
  invitation_mode: true
  bank_full_limit: 300


