spring:
  kafka:
    bootstrap-servers: 192.168.200.111:9092
    consumer:
      group-id: lzhpo
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
# 人间业火 烧不尽我
  #  security:
#    user:
#      name: zhangjunyang
#      password: 666666
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: zhangqi1112
    url: jdbc:mysql://localhost:3306/mathforhim1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
#    username: happy1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle:10
      maximum-pool-size:20
      idle-timeout:500000
      max-lifetime:540000
      connection-timeout:60000
      connection-test-query:SELECT 1




server:
  port: 80

aliyun:
  facerec:
    regionId: cn-shanghai
    accessKeyId: LTAI5tLtZSiXoBHpg1osBEX6
    accessKeySecret: JPOaJJypeV2k3yYTSMJdqCw9ME4bu1

math:
  invitation_mode: true
  bank_full_limit: 300


