spring:
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
    store-type: redis # Session store type.
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        output: # 输出通道
          destination: kafka-stream-topic-test  # 对应的topic
          contentType: application/json
        input:
          destination: kafka-stream-topic-test
          contentType: application/json
          group: kafka-stream-test # 指定消费者组
          autoRebalanceEnabled: true # 分区负载
          instanceCount: 3


# 人间业火 烧不尽我
  #  security:
#    user:
#      name: zhangjunyang
#      password: 666666
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: zhangqi1112
    url: jdbc:mysql://localhost:3306/mathforhim1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
    username: happy1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle:10
      maximum-pool-size:20
      idle-timeout:500000
      max-lifetime:540000
      connection-timeout:60000
      connection-test-query:SELECT 1




server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
  port: 80

aliyun:
  facerec:
    regionId: cn-shanghai
    accessKeyId: LTAI5tLtZSiXoBHpg1osBEX6
    accessKeySecret: JPOaJJypeV2k3yYTSMJdqCw9ME4bu1

math:
  invitation_mode: true
  bank_full_limit: 30000
  kafka_save_active: true


logging:
  level:
    root: info
    org.apache.kafka: warn

# 每个人都有TA自己的脾气，收敛住，就是成熟的表现